<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/18 21:03:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dname=symfony_tester',
  'username' => 'root',
  'password' => 'sea1sea',
  'name' => 'doctrine',
)),);
